rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx
  - ree
notifications:
  recipients:
    - drnicwilliams@gmail.com
    - memde@engineyard.com
    - srosenfeld@engineyard.com
    - jallen@engineyard.com
branches:
  only:
    - master
